### ISSUE TITLE
relation "searches" does not exist LINE 1: SELECT * FROM Searches;

### ISSUE THREAD

**Issue by QualityQuestion** [jordcart/mercaribuddy#2]
Hi there! I hope this message reaches you well! I am trying to setup your mercaribuddy bot but I am running into some issues. I have setup the discord bot without issue, and I have setup a PostgreSQL DB but I am unfortunately receiving the error in the title. 

```
mercaribuddy#sanitized has connected to Discord!
relation "searches" does not exist
LINE 1: SELECT * FROM Searches;
                      ^

Unhandled exception in internal background task 'search_loop'.
Traceback (most recent call last):
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\asdf\mercaribuddy\src\bot.py", line 187, in search_loop
    for entry in entries:
TypeError: 'NoneType' object is not iterable
```

I am not the best at databases, and I suspect that I do not have this database setup correctly or I am missing a required table or something, based off the error I am receiving, but I'm not sure where I should even start to try and fix the problem. Any guidance or other general setup advice would be greatly appreciated. Thank you :)

**Comment by jordcart** [comment]
Pushed a change that should resolve your issue. I had to add a function to create the database tables on bot startup.

**Comment by QualityQuestion** [comment]
This ultimately resolves this issue, thank you!
