### ISSUE TITLE
relation "stats" does not exist and bot doesn't respond to commands

### ISSUE THREAD

**Issue by Kyuko** [jordcart/mercaribuddy#3]
Hi, I'm currently trying to setup mercaribuddy on my PC, however I've encountered 2 problems along the way. First of which being the fact that database.py creates only Searches table while it also needs Stats table, as logs from the 1st time I ran the bot.py have shown me:
```
Discord#0000 has connected to Discord!
relation "stats" does not exist
LINE 1: UPDATE Stats SET all_users=all_users+1 WHERE name='main';
               ^

Unhandled exception in internal background task 'search_loop'.
Traceback (most recent call last):
  File "/home/kyuko/.local/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/kyuko/Downloads/mercaribuddy-master/src/bot.py", line 172, in search_loop
    result = database.verify_db_connection(connection, cursor)
  File "/home/kyuko/Downloads/mercaribuddy-master/src/database.py", line 21, in verify_db_connection
    cur.execute("SELECT;")
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```
~~Another issue is the fact that bot doesn't respond to any of my commands in the Discord channels, I'm pretty sure that its permissions are more than enough (for testing purposes added the bot as Administrator).~~

EDIT: It was due to me trying to use commands in the server instead of using them in DMs. Problem solved.

Any help in resolving these issues would be very appreciated. Thank you in advance :)

**Comment by jordcart** [comment]
Should be fixed now if you pull the latest version. The `stats` table isn't necessary so you can also feel free to remove any lines of code that reference it. I just wanted to track total stats when I was hosting the bot.
